image: 141.69.58.19:5000/iki/ros-kinetic-amr:latest

before_script:
  - source /root/catkin_ws/devel/setup.bash

stages:
    - test basic
    - test advanced

first package:
    stage: test basic
    script:
      - bash tests/01_mypackage.sh

first ros program:
    stage: test basic
    script:
      - bash tests/02_first_ros_program.sh

ros nodes:
    stage: test basic
    script:
      - bash tests/03_ros_nodes.sh

publisher:
    stage: test advanced
    script:
      - bash tests/04_publisher.sh

subscriber:
    stage: test advanced
    script:
      - bash tests/05_subscriber.sh

custom message:
    stage: test advanced
    script:
      - bash tests/06_custom_messages.sh

launch files:
    stage: test advanced
    before_script:
      - dir=`pwd`
      - cd /root/catkin_ws/src
      - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@fbe-gitlab.hs-weingarten.de/mat-iki/amr-goal-publisher.git
      - cd /root/catkin_ws/ && catkin_make
      - export ROS_LOG_DIR=`pwd`
      - source /root/catkin_ws/devel/setup.bash
      - cd $dir
    script:
      - bash tests/07_launch_files.sh

service:
     stage: test advanced
     script:
     - bash tests/08_ros_services.sh

custom service:
     stage: test advanced
     script:
     - bash tests/09_custom_service.sh
